# Generated by Django 4.2.13 on 2024-06-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipesapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="category",
        ),
        migrations.DeleteModel(
            name="RecipeCategoryRelation",
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.ManyToManyField(blank=True, to="recipesapp.recipecategory"),
        ),
    ]
